filenames = {'G:\Aineisto\D\Terratec\Hiidenportti\Laseraineisto_normalisoitu\lopulliset_alat35m000003.las',...
    'G:\Aineisto\D\Terratec\Hiidenportti\Laseraineisto_normalisoitu\lopulliset_alat35m000010.las',...
    'G:\Aineisto\D\Terratec\Hiidenportti\Laseraineisto_normalisoitu\lopulliset_alat35m000012.las',...
    'G:\Aineisto\D\Terratec\Hiidenportti\Laseraineisto_normalisoitu\lopulliset_alat35m000037.las'};

[DWStats,nonDWStats] = collectConnectedComponentTrainingData(filenames);
[nn,ca] = trainConnectedComponentClassifier(DWStats,nonDWStats);

[segments,labels] = collectTrainingSegments(filenames,0.2);
trainedNet = trainFallenTreeClassifier(segments,labels,0.05);

storer = findFallenTrees(...
    'G:\Aineisto\D\Terratec\Hiidenportti\Laseraineisto_normalisoitu\lopulliset_alat35m000001.las',...
    'connCompClassifier',nn,...
    'finalCellSize',0.05);